# Generated by Django 3.2.3 on 2023-02-13 09:27

from django.db import migrations, models
import user_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdmsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='name of user')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='user creation date')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is a admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is a staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='if a superuser')),
                ('permission', models.JSONField(default=user_auth.models.initial_user_permission, verbose_name='user permission')),
                ('reset_code', models.CharField(default=None, editable=False, max_length=32, null=True, verbose_name='password reset code')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddIndex(
            model_name='cdmsuser',
            index=models.Index(fields=['email'], name='user_auth_c_email_bf7c6c_idx'),
        ),
    ]
