# Generated by Django 4.2.4 on 2023-09-04 08:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_asset', verbose_name='file for upload')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='unique identifier for asset')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('info', models.JSONField(default=dict, verbose_name='schema info of asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.cdmsuser')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'indexes': [models.Index(fields=['identifier'], name='forecast_an_identif_242543_idx')],
            },
        ),
    ]
