# Generated by Django 3.2.5 on 2023-03-05 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forecast_source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='short name of forecast source')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name for forecast source')),
                ('lead_time', models.IntegerField(verbose_name='lead time in hours')),
                ('fcst_type', models.CharField(max_length=255, verbose_name='type of forecast eps/single')),
                ('center', models.CharField(default='', max_length=255, verbose_name='center producing forecast')),
            ],
            options={
                'verbose_name_plural': 'Forecast Source',
            },
        ),
        migrations.CreateModel(
            name='system_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=128, unique=True, verbose_name='name of the state')),
                ('init_time', models.CharField(max_length=32, verbose_name='date and sim utc time of forecast source format yyyymmdd_hh ')),
                ('info', models.JSONField(default=dict, verbose_name='additional info of the state, like netcdf header')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='field update time')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forecast_data.forecast_source')),
            ],
            options={
                'verbose_name_plural': 'System State',
            },
        ),
        migrations.AddIndex(
            model_name='forecast_source',
            index=models.Index(fields=['name'], name='forecast_da_name_51b76d_idx'),
        ),
        migrations.AddIndex(
            model_name='system_state',
            index=models.Index(fields=['state_name'], name='forecast_da_state_n_b3d0ea_idx'),
        ),
    ]
