# Generated by Django 3.2.3 on 2023-02-13 09:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Level short name')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name of level')),
            ],
            options={
                'verbose_name_plural': 'level',
            },
        ),
        migrations.CreateModel(
            name='obs_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='observation start time')),
                ('end_time', models.DateTimeField(verbose_name='observation end time')),
                ('value', models.FloatField(verbose_name='value of data')),
                ('duration', models.DurationField(default=datetime.timedelta(days=1))),
            ],
            options={
                'verbose_name_plural': 'observation_data',
            },
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True, verbose_name='Parameter short Name')),
                ('full_name', models.CharField(max_length=512, verbose_name='Parameter full name')),
                ('unit', models.CharField(max_length=32, verbose_name='Parameter unit')),
                ('parameter_type', models.CharField(choices=[('INST', 'Instant'), ('ACCM', 'Accumulated'), ('MIN', 'Minimum'), ('MAX', 'Maximum'), ('AVG', 'Average')], max_length=512)),
            ],
            options={
                'verbose_name_plural': 'parameter',
            },
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Station name')),
                ('full_name', models.CharField(max_length=512, verbose_name='Station full name')),
                ('station_id', models.CharField(blank=True, default='', max_length=512, verbose_name='Local Station id')),
                ('wmo_id', models.CharField(blank=True, default='', max_length=512, verbose_name='WMO Station id')),
                ('lat', models.FloatField(verbose_name='Station latitude')),
                ('lon', models.FloatField(verbose_name='Station longitude')),
                ('elevation', models.FloatField(default=None, null=True, verbose_name='Station elevation')),
                ('station_category', models.CharField(choices=[('MET', 'Meteorological Station'), ('HYDRO', 'Hydrological Station'), ('AGRO', 'Agrometeorological Station')], max_length=50)),
                ('station_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC STATION'), ('MANUAL', 'MANUAL STATION')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'station',
            },
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['name'], name='obs_data_st_name_1d576e_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['station_id'], name='obs_data_st_station_5da994_idx'),
        ),
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['wmo_id'], name='obs_data_st_wmo_id_bf48d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('name', 'wmo_id', 'station_id')},
        ),
        migrations.AddIndex(
            model_name='parameter',
            index=models.Index(fields=['name'], name='obs_data_pa_name_35f929_idx'),
        ),
        migrations.AddField(
            model_name='obs_data',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obs_data.level'),
        ),
        migrations.AddField(
            model_name='obs_data',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_data.parameter'),
        ),
        migrations.AddField(
            model_name='obs_data',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_data.station'),
        ),
        migrations.AddIndex(
            model_name='level',
            index=models.Index(fields=['name'], name='obs_data_le_name_7db4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='obs_data',
            index=models.Index(fields=['start_time'], name='obs_data_ob_start_t_c7835f_idx'),
        ),
        migrations.AddIndex(
            model_name='obs_data',
            index=models.Index(fields=['end_time'], name='obs_data_ob_end_tim_ad4c60_idx'),
        ),
        migrations.AddIndex(
            model_name='obs_data',
            index=models.Index(fields=['parameter'], name='obs_data_ob_paramet_c670d0_idx'),
        ),
        migrations.AddIndex(
            model_name='obs_data',
            index=models.Index(fields=['level'], name='obs_data_ob_level_i_bf026c_idx'),
        ),
        migrations.AddIndex(
            model_name='obs_data',
            index=models.Index(fields=['station'], name='obs_data_ob_station_0924f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='obs_data',
            unique_together={('start_time', 'end_time', 'parameter', 'level', 'station')},
        ),
    ]
